### ISSUE TITLE
Require cycle

### ISSUE THREAD

**Issue by mykhailo-melnyk** [patlux/react-native-bluetooth-state-manager#1]
with new React Native version we have next warning:

Require cycle: node_modules/react-native-bluetooth-state-manager/src/index.js -> node_modules/react-native-bluetooth-state-manager/src/BluetoothState/index.js -> node_modules/react-native-bluetooth-state-manager/src/BluetoothState/BluetoothState.js -> node_modules/react-native-bluetooth-state-manager/src/index.js

how can we fix it?

**Comment by patlux** [comment]
Closing because of https://github.com/patlux/react-native-bluetooth-state-manager/pull/2
