### ISSUE TITLE
Possible type error

### ISSUE THREAD

**Issue by KovaxG** [patlux/react-native-bluetooth-state-manager#21]
Hello, I'm working on a project that deals with bluetooth devices, and after we performed a typescript version upgrade, we started getting this error when running tests with Jest.

```
    TypeError: Cannot read property 'EVENT_BLUETOOTH_STATE_CHANGE' of undefined

      at Object.<anonymous> (node_modules/react-native-bluetooth-state-manager/src/BluetoothStateManager.js:4:57)
      at Object.<anonymous> (node_modules/react-native-bluetooth-state-manager/src/index.js:1:1)
```

I'm not sure whether this is a fault at our end, of it there are some incompatibilities between different versions of typescript. Do you have any suggestions?

**Comment by patlux** [comment]
Hi, are you sure this is a typescript error? It looks more like a runtime exception?

The runtime exception happens if the native modules are not correctly linked in you application. Be sure you followed the Linking steps as described [here](https://github.com/patlux/react-native-bluetooth-state-manager#linking).

**Comment by KovaxG** [comment]
I'm not sure how to resolve this because we are using react-native version 0.63.2. But in the readme it says:
>Beginning from 0.60 you don't need to link it anymore.

And reading the linked source didn't really help. Not sure what to do, to be honest.

**Comment by KovaxG** [comment]
What I forgot to mention is that we get this error when running jest, so there is no android or ios environment. Could that be the cause of the runtime exception? I think that would make the most sense.

**Comment by patlux** [comment]
Yes, that should be the problem. To make it work, add a mock implementation of `react-native-bluetooth-state-manager` to your tests.

**Comment by KovaxG** [comment]
makes sense, thanks for your help :)

**Comment by fkunecke** [comment]
@KovaxG Hey just ran into this issue, do you still have your mock code? I'm running into some issues successfully mocking this library.

**Comment by KovaxG** [comment]
Sadly this was a long time ago, working at a different company with different technologies. I don't have the source code, but I know that mocking things worked.

**Comment by fkunecke** [comment]
Thanks for the quick reply, I actually got something working :) For anyone else, here's the mock code:

```
jest.mock('react-native-bluetooth-state-manager', () => {
  return {
    default: jest.fn(),
  }
});
```

Using an auto-mock like `jest.mock('react-native-bluetooth-state-manager')` doesn't work quite right and still results in the same issue.
