### ISSUE TITLE
Remove listener when leave screen

### ISSUE THREAD

**Issue by aprakoso98** [patlux/react-native-bluetooth-state-manager#29]
How to remove subscription BluetoothStateManager.onStateChange when componentDidUnMount?

**Comment by patlux** [comment]
https://github.com/patlux/react-native-bluetooth-state-manager/blob/3c25c9bd1fa4ae7b2ce16c45c2ae7ece3ccc8ec9/example/app/ExampleWithApi.js#L21-L32

**Comment by aprakoso98** [comment]
Thanks for the reply
