### ISSUE TITLE
XCode12 Support

### ISSUE THREAD

**Issue by johnny-minty** [patlux/react-native-bluetooth-state-manager#37]
I'm unable to compile a React-Native application using XCode 12 when react-native-bluetooth-state-manager is included due to changes to XCode 12.

**Stack Error Recieved:** 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      _OBJC_CLASS_$_RNBluetoothStateManager in RNBluetoothStateManager.o
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_RNBluetoothStateManager in RNBluetoothStateManager.o
  "_RCTRegisterModule", referenced from:
      +[RNBluetoothStateManager load] in RNBluetoothStateManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**See below comments/PR's on the issue:**

https://github.com/react-native-masked-view/masked-view/pull/80/commits/f218a831525fac8399ab58f19edb5fd154d9e481
https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

**Comment by patlux** [comment]
Hi, thanks for the report. I will take a look at it.

**Comment by johnny-minty** [comment]
@patlux Furthermore to the above this error only occurs when using 'use_frameworks!' in your POD file and can be reproduced by creating a fresh project with 'react-native-bluetooth-state-manager' and use_frameworks! in your pod.
