### ISSUE TITLE
Bluetooth states order different between iOS and Android

### ISSUE THREAD

**Issue by humbkr** [patlux/react-native-bluetooth-state-manager#56]
I'm trying to implement a screen monitoring the bluetooth requirements off my app, i.e:

- if bluetooth is enabled
- if bluetooth permission has been granted

On Android, BluetoothStateManager.getState() returns:

- When bluetooth is disabled and permission is not granted: "PoweredOff"
- When bluetooth is disabled and permission is granted: "PoweredOff"
- When bluetooth is enabled and permission is not granted: "PoweredOn"
- When bluetooth is enabled and permission is granted: "PoweredOn"

=> Looks fine.

Now the same experiment on iOS:

- When bluetooth is disabled and permission is not granted: "Unauthorized"
- When bluetooth is disabled and permission is granted: "PoweredOff"
- When bluetooth is enabled and permission is not granted: "Unauthorized"
- When bluetooth is enabled and permission is granted: "PoweredOn"

=> Problem

When bluetooth is disabled and permission is not granted, bluetooth state should be "PoweredOff".
With the current behavior we have no way to really know if the bluetooth is disabled on iOS as it depends on the permission status.

We have other libs out there to check for permissions, I think this lib should focus on getting the real bluetooth state, i.e. **on** or **off**.

What do you think?

**Comment by patlux** [comment]
Hi @humbkr,

thank you for your concern. You are right, it's not treated equally on both platforms. But I think it's wrong to return `PoweredOff` when just the permission is not granted yet. You already need an another library to check and ask for permission. So if it fits your use case, then you can handle it as it would be `PoweredOff` when the permission is not granted.

I don't think this should be part of this library. The library has a single use case: Return the bluetooth status, if it can't get the status, return the reason. 

Best regards,
Patrick

**Comment by humbkr** [comment]
> The library has a single use case: Return the bluetooth status, if it can't get the status, return the reason.

That is my problem, I can't know the real status on iOS because it's dependent on the permission status.
If the bluetooth is disabled on the phone level, this library should return "PoweredOff" on iOS independently of the permission state, like on Android.

Now if it's impossible because of a technical issue on iOS, it would be useful to add this info in the readme.

**Comment by patlux** [comment]
Yes, it's technical limitation on purpose from apple due to security concerns. We can't do here anything.

Feel free to send a Pull Request to add this info to the README :)
