### ISSUE TITLE
Cannot link package in iOS

### ISSUE THREAD

**Issue by esteban-ricalde-mysa** [patlux/react-native-bluetooth-state-manager#76]
Package is working fine on Android, but it doesn't link in iOS.

I'm using react-native 0.67.2 and version 1.3.4 of react-native-bluetooth-state-manager.

I tried all the paths to create the link:
- cd ios && pod install
- running react-native link
- adding RNBluetoothStateManager to Podfile).

Always get the same result:
`WARN  react-native-bluetooth-state-manager module is not correctly linked`
followed by:
`ERROR  TypeError: null is not an object (evaluating '_RNBluetoothStateManager.default.EVENT_BLUETOOTH_STATE_CHANGE')`

and the app won't start.

Any suggestions are welcomed

**Comment by st0ffern** [comment]
```
cd ios/
pod install
cd ..
```

**Comment by esteban-ricalde-mysa** [comment]
Neither of the options to linking the module worked fine in iOS with my project. It may be some type of conflict with other existing modules. We decided to not use the module and implement our own native code to do the work
